package evaluacion2;

import javax.swing.JOptionPane;

/**
 *
 * @author Javier Suárez Guzmán
 */
public class SistemaCompra extends javax.swing.JFrame {

    /**
     * Creates new form SistemaCompra
     */
    public SistemaCompra() {
        initComponents();
        this.setLocationRelativeTo(this);
        txtNombre.setEditable(false);
        txtCodigo.setEditable(false);
        txtValor.setEditable(false);
        txtStock.setEditable(false);
        txtValorNeto.setEditable(false);
        txtValorIVA.setEditable(false);
        txtValorTotal.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoIVA = new javax.swing.ButtonGroup();
        cbTipoProducto = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtCodigo = new javax.swing.JTextField();
        txtValor = new javax.swing.JTextField();
        txtStock = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        rbtSIVA = new javax.swing.JRadioButton();
        rbtNOVA = new javax.swing.JRadioButton();
        txtValorNeto = new javax.swing.JTextField();
        txtValorIVA = new javax.swing.JTextField();
        txtValorTotal = new javax.swing.JTextField();
        btnBorrar = new javax.swing.JButton();
        btnRetornar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de compra");

        cbTipoProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Seleccionar>", "Periféricos", "Pantalla", "Discos Duros", "Otros" }));
        cbTipoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoProductoActionPerformed(evt);
            }
        });

        jLabel1.setText("Tipo de producto:");

        jLabel2.setText("Nombre");

        jLabel3.setText("Código");

        jLabel4.setText("Valor");

        jLabel5.setText("Stock");

        txtValor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtValorKeyTyped(evt);
            }
        });

        txtStock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtStockKeyTyped(evt);
            }
        });

        jLabel6.setText("IVA");

        jLabel7.setText("Valor neto");

        jLabel8.setText("Valor IVA");

        jLabel9.setText("Valor total");

        grupoIVA.add(rbtSIVA);
        rbtSIVA.setText("SI");
        rbtSIVA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtSIVAActionPerformed(evt);
            }
        });

        grupoIVA.add(rbtNOVA);
        rbtNOVA.setText("NO");
        rbtNOVA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtNOVAActionPerformed(evt);
            }
        });

        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        btnRetornar.setText("Retornar");
        btnRetornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetornarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBorrar)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel5)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRetornar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rbtSIVA)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                                .addComponent(rbtNOVA))
                            .addComponent(txtStock)
                            .addComponent(txtValor)
                            .addComponent(txtCodigo)
                            .addComponent(txtNombre)
                            .addComponent(txtValorNeto)
                            .addComponent(txtValorIVA)
                            .addComponent(txtValorTotal))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(rbtSIVA)
                    .addComponent(rbtNOVA))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtValorNeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtValorIVA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBorrar)
                    .addComponent(btnRetornar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(41, 41, 41)
                        .addComponent(cbTipoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbTipoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRetornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetornarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnRetornarActionPerformed

    private void cbTipoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoProductoActionPerformed
        int posItem = cbTipoProducto.getSelectedIndex();
        if (posItem >= 0) {
            switch (posItem) {
                case 0: //seleccione
                    txtNombre.setText("");
                    txtCodigo.setText("");
                    txtValor.setText("");
                    txtStock.setText("");
                    grupoIVA.clearSelection();
                    txtValorNeto.setText("");
                    txtValorIVA.setText("");
                    txtValorTotal.setText("");
                    break;
                case 1: //periféricos
                    txtNombre.setText("Periféricos");
                    txtCodigo.setText("100");
                    txtValor.setText("20000");
                    txtStock.setText("10");
                    txtStock.setEditable(true);
                    break;
                case 2: //pantalla
                    txtNombre.setText("Pantalla");
                    txtCodigo.setText("200");
                    txtValor.setText("80000");
                    txtStock.setText("15");
                    txtStock.setEditable(true);
                    break;
                case 3: //discos duros
                    txtNombre.setText("Discos duros");
                    txtCodigo.setText("300");
                    txtValor.setText("120000");
                    txtStock.setText("50");
                    txtStock.setEditable(true);
                    break;
                case 4: //otros
                    txtNombre.setText("Otros");
                    txtCodigo.setText("400");
                    txtValor.setText("Ingrese valor");
                    txtValor.setEditable(true);
                    txtStock.setText("Ingrese stock");
                    txtStock.setEditable(true);
                    txtValor.requestFocus();
                    break;
            }
        }
    }//GEN-LAST:event_cbTipoProductoActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        cbTipoProducto.setSelectedIndex(0);
        txtNombre.setText("");
        txtCodigo.setText("");
        txtValor.setText("");
        txtStock.setText("");
        grupoIVA.clearSelection();
        txtValorNeto.setText("");
        txtValorIVA.setText("");
        txtValorTotal.setText("");
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void txtValorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorKeyTyped
        char isNumeric = evt.getKeyChar();
        if (Character.isLetter(isNumeric)) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "El valor debe ser numérica");
        }
    }//GEN-LAST:event_txtValorKeyTyped

    private void txtStockKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStockKeyTyped
        char isNumeric = evt.getKeyChar();
        if (Character.isLetter(isNumeric)) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "El valor debe ser numérica");
        }
    }//GEN-LAST:event_txtStockKeyTyped

    private void rbtSIVAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtSIVAActionPerformed
        int posItem = cbTipoProducto.getSelectedIndex();
        if (posItem > 0) {
            int stock = Integer.parseInt(txtStock.getText());
            int valorNeto = Integer.parseInt(txtValor.getText());//convierto txtValor a int para hacer los calculos 
            int valorIVA, valorTotal; //declaro todo int despues casteo
            valorNeto = (int) valorNeto * stock;
            valorIVA = (int) (valorNeto * 0.19) * stock;
            valorTotal = (int) (valorNeto * 1.19) * stock;
            if (valorNeto > 0 && stock > 0) {
                txtValorNeto.setText(Integer.toString(valorNeto));
                txtValorIVA.setText(Integer.toString(valorIVA));
                txtValorTotal.setText(Integer.toString(valorTotal));
            } else {
                JOptionPane.showMessageDialog(null, "El stock y el valor deben ser mayores que 0");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un producto");
        }
    }//GEN-LAST:event_rbtSIVAActionPerformed

    private void rbtNOVAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtNOVAActionPerformed
        int posItem = cbTipoProducto.getSelectedIndex();
        if (posItem > 0) {
            int stock = Integer.parseInt(txtStock.getText());
            int valorNeto = Integer.parseInt(txtValor.getText());//convierto txtValor a int para hacer los calculos 
            valorNeto = (int) valorNeto * stock;
            if (valorNeto > 0 && stock > 0) {
                txtValorIVA.setText("");
                txtValorNeto.setText(Integer.toString(valorNeto));
                txtValorTotal.setText(Integer.toString(valorNeto));
            } else {
                JOptionPane.showMessageDialog(null, "El stock y el valor deben ser mayores que 0");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un producto");
        }
    }//GEN-LAST:event_rbtNOVAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SistemaCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SistemaCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SistemaCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SistemaCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SistemaCompra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnRetornar;
    private javax.swing.JComboBox<String> cbTipoProducto;
    private javax.swing.ButtonGroup grupoIVA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rbtNOVA;
    private javax.swing.JRadioButton rbtSIVA;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtStock;
    private javax.swing.JTextField txtValor;
    private javax.swing.JTextField txtValorIVA;
    private javax.swing.JTextField txtValorNeto;
    private javax.swing.JTextField txtValorTotal;
    // End of variables declaration//GEN-END:variables
}
